import { useEffect, useState } from "react";
import { listSamples } from "../lib/api";
import type { SampleSpec } from "../lib/types";

export function SampleGallery({
  onRunSample, disabled,
}: {
  onRunSample: (sampleId: string) => void;
  disabled?: boolean;
}) {
  const [samples, setSamples] = useState<SampleSpec[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    listSamples()
      .then((r) => setSamples(r.samples))
      .catch((e) => setError(e instanceof Error ? e.message : String(e)));
  }, []);

  if (error || (samples && samples.length === 0)) return null;

  return (
    <div style={{ marginTop: 26 }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginBottom: 6 }}>
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 16, fontWeight: 600, margin: 0, color: "var(--text-primary)" }}>
          No recording handy? Try one of these
        </h2>
        <div style={{ flex: 1, height: 1, background: "var(--border-hairline)" }} />
      </div>
      <div style={{ fontSize: 12, color: "var(--text-tertiary)", marginBottom: 14, lineHeight: 1.5 }}>
        One click loads the signal and runs the complete pipeline. These are <strong style={{ color: "var(--status-hypothesized)" }}>synthetic
        signals</strong> generated by this platform's own signal generator &mdash; not off-air captures &mdash; which is
        precisely why their ground truth is known exactly, and shown below so you can check the pipeline's answer against it.
      </div>

      {samples === null ? (
        <div style={{ color: "var(--text-tertiary)", fontSize: 12.5 }}>Loading samples&hellip;</div>
      ) : (
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 12 }}>
          {samples.map((s) => (
            <div
              key={s.id}
              className="panel"
              style={{ padding: 16, display: "flex", flexDirection: "column", gap: 10, opacity: disabled ? 0.55 : 1 }}
            >
              <div>
                <div style={{ fontSize: 13.5, fontWeight: 600, color: "var(--text-primary)", marginBottom: 4 }}>
                  {s.title}
                </div>
                <div style={{ fontSize: 11.5, color: "var(--text-secondary)", lineHeight: 1.5 }}>
                  {s.description}
                </div>
              </div>

              <div style={{ display: "flex", flexWrap: "wrap", gap: 4 }}>
                {s.highlights.map((h) => (
                  <span
                    key={h}
                    style={{
                      fontSize: 9.5, padding: "2px 7px", borderRadius: 999,
                      background: "var(--status-estimated-dim)", color: "var(--status-estimated)",
                      border: "1px solid var(--status-estimated)33",
                    }}
                  >
                    {h}
                  </span>
                ))}
              </div>

              <div style={{ background: "var(--bg-inset)", borderRadius: "var(--radius-sm)", padding: "8px 10px", border: "1px solid var(--border-hairline)" }}>
                <div style={{ fontSize: 9, color: "var(--text-tertiary)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4 }}>
                  Known ground truth
                </div>
                {Object.entries(s.expected).map(([k, v]) => (
                  <div key={k} className="mono" style={{ display: "flex", justifyContent: "space-between", fontSize: 10.5, padding: "1px 0" }}>
                    <span style={{ color: "var(--text-tertiary)" }}>{k}</span>
                    <span style={{ color: "var(--text-secondary)" }}>{String(v)}</span>
                  </div>
                ))}
              </div>

              <button
                onClick={() => onRunSample(s.id)}
                disabled={disabled}
                style={{
                  padding: "8px 12px", borderRadius: "var(--radius-md)", border: "none",
                  background: disabled ? "var(--bg-panel-raised)" : "var(--grad-waterfall)",
                  color: disabled ? "var(--text-tertiary)" : "#0a0d10",
                  fontWeight: 700, fontSize: 12.5, cursor: disabled ? "default" : "pointer",
                  fontFamily: "var(--font-display)", marginTop: "auto",
                }}
              >
                {"\u25B6"} Load &amp; Analyze
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
